// vendored from https://github.com/slidevjs/slidev/blob/main/packages/client/styles/layouts-base.css
import './layouts-base.scss'
import '@alvarosabu/ui/styles'
import './colors.scss'
import './fonts.css'
import './layout.scss'
import './custom.css'
import './typography.scss'
import 'uno.css'
import './overrides.scss'
